# Generated by Django 2.2.7 on 2020-01-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prone', '0002_context_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='videofile',
            field=models.FileField(null=True, upload_to='prone/videos', verbose_name=''),
        ),
    ]
