# Generated by Django 2.2.7 on 2020-01-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prone', '0003_auto_20200110_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='videofile',
        ),
        migrations.AddField(
            model_name='context',
            name='vid',
            field=models.FileField(default='', upload_to='prone/images'),
        ),
    ]
