# Generated by Django 2.2.7 on 2020-01-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prone', '0004_auto_20200110_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='vid',
            field=models.FileField(null=True, upload_to='prone/videos', verbose_name=''),
        ),
    ]
