# Generated by Django 2.2.7 on 2020-01-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prone', '0005_auto_20200110_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='vid',
            new_name='vide',
        ),
    ]
